version: "2"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    env_file: ./lib/postgres.env
  db:
    image: postgres
    env_file: ./lib/postgres.env
    volumes:
      - ./lib/init.sql:/docker-entrypoint-initdb.d/init.sql
