version: "2"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: postgres
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql

